version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-sulwork
    restart: always
    environment:
      POSTGRES_USER: ${user_db}
      POSTGRES_PASSWORD: ${password_db}
      POSTGRES_DB: sulwork
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sulwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${user_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: sulwork-app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${url_db}
      SPRING_DATASOURCE_USERNAME: ${user_db}
      SPRING_DATASOURCE_PASSWORD: ${password_db}
    ports:
      - "8081:8080"
    networks:
      - sulwork

volumes:
  postgres-data:

networks:
  sulwork:
    driver: bridge