services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: mysql-sulwork
    environment:
      POSTGRES_USER: ${user_db}
      POSTGRES_DB: sulwork
      POSTGRES_PASSWORD: ${password_db}
    ports:
      - '5432:3306'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sulwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready ping -h ${url_db} -u ${user_db} -p ${password_db}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    container_name: sulwork-app
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${url_db}
      SPRING_DATASOURCE_USER: ${user_db}
      SPRING_DATASOURCE_PASSWORD: ${password_db}
    ports:
      - "8081:8080"
    networks:
      - sulwork

volumes:
  postgres-data:

networks:
  sulwork:
    driver: bridge